### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by daxtep** [jc9108/ttv-favorites#3]
Is it just me or does the addon not work anymore?

**Comment by jc9108** [comment]
idk, works for me. havent had any other reports.

are you on the latest version v=1.2.4 ?

can you open the devtools console ctrl+shift+j on a channel page on twitch.tv and see if there are any errors from foreground.js ?

**Comment by jc9108** [comment]
@LasstMichLiegen thanks for reporting. the friendlist is gone for me too but i cannot replicate the issue.

> can you open the devtools console `ctrl+shift+j` on a channel page on twitch.tv and see if there are any errors from `foreground.js` ?

**Comment by LasstMichLiegen** [comment]
this message comes if i want to add an fav. 

foreground.js:1 foreground
foreground.js:376 Object
foreground.js:380 Set(3)
foreground.js:390 Object
foreground.js:394 channel
foreground.js:211 TypeError: Cannot read properties of null (reading 'querySelector')
    at update_channels_lists (foreground.js:326:53)
    at remove_favorite (foreground.js:163:2)
    at HTMLButtonElement.<anonymous> (foreground.js:209:41)
(anonymous) @ foreground.js:211

**Comment by jc9108** [comment]
probably a twitch update that you guys received that hasnt rolled out to me yet. i cant fix it until i see the changes, so i will fix it as soon as i get the update.

thanks for your understanding & patience.

**Comment by OG-Bread** [comment]
> Is it just me or does the addon not work anymore?

Nah my guy, it still working for me. 

I'm using :
-Brave Browser Version 1.39.111 Chromium: 102.0.5005.61
-BetterTTV 7.4.29 (if that matters)

**Comment by peacachucarrots** [comment]
Still works for me as well, I'm using google chrome and v1.3.4 of the extension.

**Comment by jc9108** [comment]
it is also still working for me at this time. maybe it's just you two then @daxtep @LasstMichLiegen

can you try this: go to `chrome://extensions` and reload the extension and then reload any twitch.tv pages you have open. see if that fixes it

**Comment by LasstMichLiegen** [comment]
Hi. It is still not working :( my buddy doesn't do it either

her is a desktop capture [https://www.youtube.com/watch?v=VL81Uvv_fnA](https://www.youtube.com/watch?v=VL81Uvv_fnA)

**Comment by jc9108** [comment]
ah you are using german language on twitch. i just tested it in german and other non-english languages and it doesnt work anymore, so you are right (but it is still working in english). thanks for showing me this @LasstMichLiegen. i will look into it

**Comment by jc9108** [comment]
fixed with 1f38d35. you should get this update in a few days when cws approves it

**Comment by jc9108** [comment]
actually the update got approved immediately. so you can get it as of now. please confirm v=1.2.5 works for you @daxtep @LasstMichLiegen

**Comment by jc9108** [comment]
fixed with 1f38d35. the update just got approved by cws. please confirm v=1.2.5 works for you @daxtep @LasstMichLiegen

**Comment by LasstMichLiegen** [comment]
yes its works fine now. thx :)

**Comment by daxtep** [comment]
> fixed with [1f38d35](https://github.com/jc9108/ttv-favorites/commit/1f38d3529e74831d7aa0e59b157a82c181a4d918). the update just got approved by cws. please confirm v=1.2.5 works for you @daxtep @LasstMichLiegen

sorry, won't be home until thursday. I'll test then. Thank you for the fix and the tool!
